# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3296ed554b9418d0c885e7e32e2698e6fe7b8c619416ad1db3d360230b132c87d7cc4a172e4bba5015122e13f3e7cee2bcbd15d20babf5b2cb18540ea2f8bfbe

test:
  secret_key_base: 38efc9fcf79592462cd66c78d9caba6199a256a24a6bcb69ae7e2bbf3079a109843cb172c474f768d1c4500a53cc4006a48f7d4541c39374755486de278e772b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
